# Generated by Django 5.2.1 on 2025-07-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
