# Generated by Django 5.2.1 on 2025-07-05 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbersite', '0002_barberwallet'),
        ('customersite', '0005_alter_booking_options_alter_booking_barber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barbersite.barberslot'),
        ),
    ]
