# Generated by Django 5.2.1 on 2025-07-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersite', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='travel_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('STARTED', 'Started'), ('ON_THE_WAY', 'On the Way'), ('ALMOST_NEAR', 'Almost Near'), ('ARRIVED', 'Arrived')], default='NOT_STARTED', max_length=20),
        ),
    ]
