# Generated by Django 5.2.1 on 2025-07-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersite', '0009_customerwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('REQUESTED', 'Requested'), ('READY', 'Ready'), ('WAIT', 'Wait'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_REQUESTED', max_length=20),
        ),
    ]
