# Generated by Django 5.2.1 on 2025-07-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customersite', '0010_booking_service_started_at_booking_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service_status',
        ),
    ]
