# Generated by Django 5.2.1 on 2025-07-25 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersite', '0013_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='customersite.booking'),
        ),
    ]
