# Generated by Django 5.2.1 on 2025-08-03 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0003_remove_adminwallettransaction_transaction_type'),
        ('barbersite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='barberservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='adminsite.servicemodel'),
        ),
    ]
