# Generated by Django 5.2.1 on 2025-07-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0002_coupon_is_active_coupon_max_usage_per_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminwallettransaction',
            name='transaction_type',
        ),
    ]
