# Generated by Django 5.2.1 on 2025-08-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0003_remove_adminwallettransaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='max_usage_per_customer',
        ),
    ]
