# Generated by Django 5.2.1 on 2025-07-25 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0004_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('customer_payment', 'Customer Payment'), ('barber_payout', 'Barber Payout'), ('platform_fee', 'Platform Fee')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='adminsite.adminwallet')),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
