# Generated by Django 5.2.1 on 2025-07-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_reg', '0002_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberrequest',
            name='registration_step',
            field=models.CharField(choices=[('personal_details', 'Personal Details'), ('otp_verified', 'OTP Verified'), ('documents_uploaded', 'Documents Uploaded'), ('under_review', 'Under Review'), ('completed', 'Completed')], default='personal_details', max_length=20),
        ),
    ]
